### ISSUE TITLE
api 명세 관련

### ISSUE THREAD

**Issue by LLProject-KR** [loveliveall/loveliveall#1]
안녕하세요.

다음과 같은 API를 요청 드립니다. 

today_schedule (GET) 

input
별도의 파라미터 값 없음

output 

```
"schedule_list": [
{
	"start_date": 1676948400,
	"end_date": 1688309940,
        "title": "ラブライブ！虹ヶ咲学園スクールアイドル同好会 にじたび！ TOKIMEKI FAN MEETING TOUR（大阪公演）"			
	"category": "lovelive", 
	"url": "https:\/\/www.lovelive-anime.jp\/nijigasaki\/live\/live_detail.php?p=fanmeeting2023"
	"cast": [
			{
			       "name": "하야시 코코",
			},
			{
				"name": "호모토 아키나",
			}, ...
		 ],
	"description": "会場：オリックス劇場\nDAY.1 7月1日（土）17：00開場／18：00開演\nDAY.2 ＜昼公演＞ 7月2日（日）12：00開場／13：00開演\n    　　＜夜公演＞ 7月2日（日）16：00開場／17：00開演", 
},
...
]
```

category 부분은 non_lovlive 인지 lovelive 인지 정도로 구분하면 될 것 같습니다.

api 실행 주기는 아마도 interval하게 10분 단위로 스케쥴러 돌릴 듯 합니다.

**Comment by loveliveall** [comment]
```
{
  start_date: number;
  end_date: number;
  title: string;
  category: "lovelive" | "non_lovelive";
  url: string;
  cast: { name: string }[];
  description: string;
}[]
```

몇 가지 질문 드립니다:
- today_schedule API는 두 가지 안이 있을 것으로 보입니다: API의 요청 시점부터 24시간 (86400초) 이내의 일정을 가져오기 or API의 요청 시점을 기준으로 해당 날짜(UTC+9 기준)의 0시부터 24시까지의 일정을 가져오기. 두 가지 중 어느쪽을 선호하시나요?
- `cast` 필드는 `{ name: string }[]` 형태의 데이터를 원하시는 것 같은데, `string[]` 이 아닌 별도의 이유가 있을까요? (ex, `"cast": ["하야시 코코", "호모토 아키나", ...]`). 이름 이외의 별도 정보가 필요하지 않다면 전송 데이터량 측면에서 이렇게 바꾸는게 나아 보입니다.
- `category` 구분을 `non_lovelive` / `lovelive` 로만 하실 생각이면 대신 `is_lovelive: boolean` 형태의 필드로 대체하는건 어떻게 생각하시나요?

**Comment by LLProject-KR** [comment]
아침에 조금 정신없어서 제가 위의 output을 제대로 신경 못 쓴 부분이 보이는군요.

1. 후자로 부탁드립니다.

2. 이름 이외의 정보가 나중에 가서 필요할 것 같아서(예를 들어서 중도 하차하거나 졸업한 성우들에 대한 정보가 필요한 경우) 저런 식으로 했습니다만, 굳이 그럴 필요는 없어 보이긴 하네요.
string[]으로 하는 게 좋겠네요.

3. 말씀하신 대로 boolean 형태로 하는 게 좋을 듯합니다.

**Comment by loveliveall** [comment]
API 가 제작되어 배포되었습니다. 아래 상세 명세 전달드립니다.

## Today Schedule List API
- Request endpoint: https://cal-api.llasfans.net/api/v1/today-schedule
- Content-Type: application/json
- Response body type:
```typescript
type V1GetTodayScheduleRes = {
  schedule_list: {
    id: string; // Unique identifier for event.
    start_date: number; // Start of the event represented in epoch time.
    end_date: number; // End of the event represented in epoch  time.
    title: string; // Title of the event.
    is_lovelive: boolean; // Indicates whether this event is related to LoveLive! franchise.
    url: string; // URL related to the event. Can be empty string.
    cast: string[]; // List of cast names related to the event.
    description: string; // Description of the event. Can be empty string.
  }[];
};
```

### Request Example
```http
GET https://cal-api.llasfans.net/api/v1/today-schedule HTTP/1.1
```

### Response Body Example
```json
{
  "schedule_list": [
    {
      "id": "0A9nYPiT4osqYsj8Ueuhh",
      "title": "스쿠페스 시리즈 감사제 2023 개최 기념! 러브라이브! 슈퍼스타!! 하라주쿠 타케시타 도오리 잭 & 점포 콜라보",
      "description": "하라주쿠 타케시타 도오리에서 스쿠페스 감사제 콜라보를 한다고 함\n공지: https://www.lovelive-anime.jp/yuigaoka/topics/detail.php?p=01_2154",
      "start_date": 1687273200,
      "end_date": 1688914740,
      "is_lovelive": true,
      "url": "https://twitter.com/LoveLive_staff/status/1671324074113646594",
      "cast": [
        "다테 사유리",
        "Liyuu",
        "미사키 나코",
        "페이튼 나오미",
        "아오야마 나기사",
        "스즈하라 노조미",
        "야부시마 아카네",
        "오오쿠마 와카나",
        "에모리 아야"
      ]
    },
    {
      "id": "3aX7zfWDK9ri8KKVNXeEP",
      "title": "「러브라이브! 하스노소라 여학원 스쿨 아이돌 클럽」 오피셜 타이업 샵 by 게마즈",
      "description": "카나자와에 게마즈가 기간 한정으로 출점\n공지: https://www.lovelive-anime.jp/news/01_1960.html\nhttps://www.gamers.co.jp/shop/detail.php?id=22\nhttps://twitter.com/kanazawa_gema",
      "start_date": 1682607600,
      "end_date": 1693753140,
      "is_lovelive": true,
      "url": "https://www.lovelive-anime.jp/news/01_1960.html",
      "cast": [
        "니레이 노조미",
        "노나카 코코나",
        "하나미야 니나",
        "사사키 코토코",
        "칸 칸나",
        "츠키네 코나"
      ]
    },
    // some more events will follow...
  ]
}
```

### Notes
- 해당 엔드포인트는 15분에 10회의 call만 할 수 있도록 rate limit을 걸어 두었습니다. 해당 제한을 완화하길 원하시는 경우 별도로 알려주세요.
- 일부 일정의 경우 종료 시간이 명확하지 않으나 (ex. 라이브 이벤트 등) 애플리케이션 특성상 유저들이 임의로 정해 등록해둔 값으로 내려갈 수 있습니다.


사용해보신 후 추가 논의 사항이 있으시면 이 이슈에 달아주시고, 아닐경우 이슈 닫아주시면 감사하겠습니다.

+) 추후 변경사항이 발생하거나 할 경우 이 이슈를 통해 안내드리도록 하겠습니다.

**Comment by LLProject-KR** [comment]
한가지 추가할 점이 있어서 연락 드립니다.
```
{
  ...
  category: string,
  ...
}
```
위의 key-value 값도 필요할 것 같습니다.

필요에 따라서 '선행권/티켓 정보' 같은 것은 노출하지 않으려고 하는데, 카테고리가 없으니 분류하기 조금 힘드네요. 

감사합니다.

**Comment by loveliveall** [comment]
카테고리 정보가 추가되어 API가 배포되었습니다.

그리고 지난번에 안내드릴때 깜빡한게 있는데, `https://cal.llasfans.net/event/<event_id>` (ex. `https://cal.llasfans.net/event/0A9nYPiT4osqYsj8Ueuhh`) 형태의 URL로 접근하면 캘린더 일정 상세를 바로 볼 수 있는 화면으로 리다이렉트 됩니다. 이용에 참고해주세요.
